---
nginx_events_params:
  - worker_connections {{ nginx_max_clients | default('512') }}
nginx_group: "{{ nginx_user }}"
nginx_http_params:
  - sendfile on
  - tcp_nopush on
  - tcp_nodelay on
  - keepalive_timeout 65
  - types_hash_max_size 2048
nginx_log_dir: /var/log/nginx
nginx_log_formats:
  upstream: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $upstream_addr $upstream_status"
nginx_site_configs: {}
nginx_user: "www-data"
nginx_worker_processes: "{{ ansible_processor_vcpus | default('auto') }}"
